# Generated by Django 5.1.1 on 2024-11-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_remove_order_address_remove_order_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
