# Generated by Django 5.1.1 on 2024-11-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_order_grand_total_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUND', 'Refund'), ('DISPATCH', 'Dispatch')], default='Pending', max_length=20),
        ),
    ]
