# Generated by Django 5.1.1 on 2024-12-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0007_remove_order_cancelation_reson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
