# Generated by Django 5.1.1 on 2024-12-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0008_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
