# Generated by Django 5.1.1 on 2024-12-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0009_order_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='N/A', max_length=254, verbose_name='Customer Name'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default='N/A', max_length=36, verbose_name='Payment ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Cancelled', 'Cancelled')], default='Pending', max_length=254, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='provider_order_id',
            field=models.CharField(default='N/A', max_length=40, verbose_name='Order ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='signature_id',
            field=models.CharField(default='N/A', max_length=128, verbose_name='Signature ID'),
        ),
    ]
