# Generated by Django 5.1.1 on 2025-01-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0011_order_cancellation_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI Payment'), ('paypal', 'paypal'), ('cod', 'Cash on Delivery'), ('wallet', 'Wallet')], max_length=20),
        ),
    ]
