# Generated by Django 5.1.1 on 2025-01-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0015_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
    ]
