# Generated by Django 5.1.1 on 2025-01-30 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0015_coupon_cart_coupon'),
        ('order_app', '0017_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_order', to='cart_app.cart'),
        ),
    ]
