# Generated by Django 5.1.1 on 2024-11-28 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_app', '0002_wishlist_variant_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
    ]
