# Generated by Django 5.1.1 on 2024-10-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_flavour_product_flavor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='flavor',
            new_name='flavour',
        ),
    ]
