# Generated by Django 5.1.1 on 2024-10-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_product_flavour'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flavour',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
