# Generated by Django 5.1.1 on 2024-11-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
