# Generated by Django 5.1.5 on 2025-01-31 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_review_prdct_images_reviewhelpful'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
