# Generated by Django 5.1.1 on 2024-11-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0007_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
