# Generated by Django 5.1.1 on 2024-11-21 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0008_remove_orderitem_order_remove_orderitem_product_and_more'),
        ('dashboard', '0019_variant_sku_variant_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.variant'),
        ),
    ]
