# Generated by Django 5.1.1 on 2024-11-21 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0012_alter_cartitem_variant'),
        ('dashboard', '0019_variant_sku_variant_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_cart', to='dashboard.variant'),
        ),
    ]
