# Generated by Django 5.1.1 on 2024-11-02 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
