# Generated by Django 5.1.1 on 2024-11-11 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_address_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercontact',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='usercontact',
            constraint=models.UniqueConstraint(fields=('user', 'mobile_number'), name='unique_user_mobile'),
        ),
    ]
